dtb-$(CONFIG_ARCH_MXC) += mcm-imx8m-mini.dtb
dtb-$(CONFIG_ARCH_MXC) += mcm-imx8m-mini-thermal.dtb
dtb-$(CONFIG_ARCH_MXC) += sbc-mcm-imx8m-mini.dtb
dtb-$(CONFIG_ARCH_MXC) += sbc-mcm-imx8m-mini-rs485.dtb

always         := $(dtb-y)
subdir-y       := $(dts-dirs)
clean-files    := *.dtb
