#
# Makefile for custom.
# Vincent Stehlé <vincent.stehle@freescale.com>
#

obj-$(CONFIG_CUSTOM_HELLO)	+= hello.o
obj-$(CONFIG_CUSTOM_SCULL)	+= scull_main.o
obj-$(CONFIG_CUSTOM_SDMA)	+= custom_sdma.o
